### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by lmarburger**
Now that the gem and Rails API are proven to work together, it's time to rebuild the gem to have tests and a better UI. Here's how I've been imagining it will work. @eric I'd love your feedback. 

``` ruby
options = { :service_url    => 'http://my-hosted-pilfer.com',
            :service_token  => 'abc123',
            :file_matcher   => %r{...},
            :app_root       => '/dev/null',
            :checker        => lambda { run_profile? } }

Pilfer::Profiler.profile(options) { do_work }

Pilfer.profile(options) { do_work }

use(Pilfer::Middleware, :service_url    => 'http://my-hosted-pilfer.com',
                        :service_token  => 'abc123',
                        :file_matcher   => %r{...},
                        :app_root       => '/dev/null') do
  run_profile?
end
```

I'm not very happy with the mess of options needed for the code block usage. I think extracting the object that does the reporting from the object that profiles is where I'm headed. You'll instantiate a `Pilfer::Reporter` and pass it to `Pilfer.profile`.

My biggest focus is on the middleware since that's the first thing that'll be running in production. Once we have use cases for profiling arbitraty blocks of code, we can figure out how it makes sense to design the UI.

### CODE REVIEW

**Comment by eric** [comment]
I'm not sure I like the idea of the class method on `Pilfer::Profiler`.

I expect in general you would create an instance of `Pilfer::Profiler` with the correct options for your project, and then run `Pilfer::Profiler#profile()` when you want to profile a block of code.

I'm torn if the `checker` belongs in `Pilfer::Profiler` or in the middleware, etc.

I can see arguments for both.

For now maybe we'll start with the checker just on the middleware

I believe `:file_matcher` is something that we'll want to pass into the `#profile()` method, but most of the other options are going to be things that are the same project-wide.

**Comment by lmarburger** [comment]
All great feedback. My thought was the stand-alone code profiling would make use of a `checker` but I'll pull it out until it's a legitimate use.

I like to use class methods for convenience when there's a common path to doing something and creating an instance of an object first gets in your way.

``` ruby
Profiler.new(:service_url => '...',
             :service_token => '...').
        profile(:file_matcher => %r{...}) do
  do_work
end

# Creates and instance and calls #profile under the hood.
Profiler.profile(:service_url => '...',
                 :service_token => '...',
                 :file_matcher => %r{...}) do
  do_work
end
```

I think the middleware should create an instance of a `Pilfer::Profiler` and some reporter object instead of each time a request comes in. That may obviate the need for the convenience class method.

**Comment by eric** [comment]
I agree we should be doing things to allow for lots of the options to be set on the instance or overridden at the time of calling `profile()`, but here were some thoughts I had:
1. I'm going to want to be using this profiler both from middleware and in things like resque jobs
2. The service location and token are going to be consistent across all invocations, but the `:file_matcher` will depend on what it is that I'm interested in profiling for that specific profile request

I definitely agree that we should make passing in a constructed `Profiler` object to the middleware should be optional, and that just passing in the service info should be just fine, to make it easier.

**Comment by lmarburger** [comment]
@eric In playing with the API some more, I'd like to get your opinion on a few things.

#### Default `app_root` value

``` ruby
app_root = ENV['PWD']
reporter = Pilfer::Logger.new 'pilfer.log', app_root: app_root
```

Do you see any reason why `$PWD` shouldn't be the default `app_root`? (`app_root` is simply the part of the file path that's trimmed for display purposes only. So `app/models/user.rb` is presented instead of `/Users/Larry/Sites/my_awesome_rails_app/app/models/uesr.rb`.) If the absolute path is desired, `app_root: nil` could be used.

#### `Logger` API

``` ruby
Pilfer::Logger.new('pilfer.log')
Pilfer::Logger.new($stdout)
```

For my purposes, I only care about logging to actual files. Do you have objections to eliminating the option to pass an `IO` object and instead always expect a path? If you like the flexibility of passing an `IO`, can you think of a good API I could use to model the implementation?

**Pull request merged**
